AWSTemplateFormatVersion : '2010-09-09'
Description: Lambda Blueprint Stack
Transform: AWS::Serverless-2016-10-31
  
Globals:
  Function:
    AutoPublishAlias: live
    MemorySize: 128
    Runtime: go1.x
    Timeout: 60

Resources:
  ApiGatewayFct:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lambda-blueprint-api-fct
      Description: Lambda function triggered by an API gateway request
      Handler: bin/api
      Events:
        Vote:
          Type: Api
          Properties:
            Path: /
            Method: get
  
  ScheduleFct:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lambda-blueprint-schedule-fct
      Description: Lambda function triggered by a schedule event
      Handler: bin/schedule
      Events:
        Schedule:
          Type: Schedule # see https://docs.aws.amazon.com/lambda/latest/dg/tutorial-scheduled-events-schedule-expressions.html
          Properties:
            Schedule: rate(1 minute)

Outputs:
  Api:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
